bankingproject/bank/urls.py
from django.urls import path
from .import views
app_name='bank'
urlpatterns = [
    path('',views.alldiscat,name='alldiscat'),
    path('<slug:c_slug>/', views.alldiscat,name='district_by_branch'),
    path('<slug:c_slug>/<slug:district_slug>/', views.pdtdetail,name='disbradetail')

]

bankingproject/bankingproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bank.urls')),
    path('office/',include('office.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingproject/bank/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Branch(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='branch', blank=True)

    def get_url(self):
        return reverse('bank:district_by_branch', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'branch'
        verbose_name_plural = 'Branches'

    def __str__(self):
        return '{}'.format(self.name)

class District(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    branch=models.ForeignKey(Branch,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='district',blank=True)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('bank:disbradetail',args=[self.branch.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'district'
        verbose_name_plural = 'Districts'

    def  __str__(self):
        return '{}' .format(self.name)

bankingproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href= "{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}"
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>
</body>
</html>

bankingproject/templates/branch.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if branch %}
    {{branch.description|truncatewords:155}}
      {% else %}
        welcome banking
      {% endif %}
    {% endblock %}
  {% block title %}

{% if branch %}
<!--       {{ category.name}}-->
         {% else %}

         {% endif %}
       {% endblock %}

{% block content %}
{% if branch %}
<div>
    <div class="row my_row_class">
        <div class="mx_auto">
        <p><a href="{% url 'bank:alldiscat' %}"></a></p>
        </div>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if branch %}
    <img class="my_image" src="{{branch.image.url}}" alt="{{branch.name}}" style="width:300px;height:200px">
</div>
<br>
<div>
    <h1 class="my_title">{{branch.name}}</h1>
    <p class="text-justify">{{branch.description}}</p>
</div>
{% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/bannar.png' %}" alt="our products" width="1000px" height="1000px">
</div>
<br>
<div>
    <h1 class="text-center my_title">Banking and Finance</h1>
    <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for district in districts.object_list %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card h-100 text-center">
                <a href="{{district.get_url}}"><img class="card-img-top" src="{{district.image.url}}" alt="{{district.name}}" height="150px"></a>
                <div class="card-body">
                    <h4>{{district.name}}</h4>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
    <div class="mx_auto">
        {% if districts.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in districts.paginator.page_range %}
                <a href="?page={{pg}}"  class="btn btn-light btn-sm {% if districts.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

bankingproject/templates/district.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ district.description|truncatewords:155 }}


{% endblock %}
{% block title %}
    {% if branch %}
        {{ district.name }} - banking
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_pdt_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'bank:alldiscat' %}">Home</a> | <a  href="{{district.branch.get_url}}">{{district.branch}}</a> | {{branch.name}}</p>
    </div>
</div>
<div class="container">
    <br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img class="my_image" src="{{district.image.url}}" alt="{{district.name}}">
        </div>
    </div>
  <div class="col-12 col-sm-12 col-md-12 col-lg-6">
      <div>
          <h1 class="my_pdt_title"><b>{{district.name}}</b></h1>
          <p class="my_title">Branch description</p>
        <p class="text-justify my_pdt_text">{{district.description}}</p>
      </div>
</div>
</div>
</div>
{% endblock %}

bankingproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy;2023. All Rights Reserved</p>
</div>

bankingproject/templates/form.html
<body style="background-color:light blue;color:green;text-align:center;margin-top:250px">
    <h4>THANKYOU</h4>
    <h1> Application accepted </h1>

<form action="form" method="get">
<!--    <button type="submit" class="btn btn-warning" style="background-color:yellow;font-size:50px;padding:15px 32px;border-radius:12px;box-shadow:0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19">Ok</button>-->
<a href="http://127.0.0.1:8000" class="btn btn-success"><h2>OK</h2></a>
</form>
</body>

bankingproject/templates/header.html
{% load static %}

<header >
    <center>

 <a href="{% url 'bank:alldiscat' %}"></a><img src="{% static 'img/logo.png'%}" alt="logoimage" width="150px;" height="150px">
    </center>
</header>

bankingproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body style="background-color:#DB7093;">
<h2 style="text-align:center;margin-top:70px" >LOGIN</h2>
<form action="login" method="POST" style=" background-color:PaleVioletRed;text-align:center;padding:10px">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter your username"><br>
    <input type="password" name="password" placeholder="enter your password"><br>
    <input type="submit"><br>
    <a href="http://127.0.0.1:8000/office/register" class="btn btn-success"><h2>Register</h2></a>
</form>
</body>
</html>

bankingproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'bank' in request.path%} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branches
                </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'bank:alldiscat' %}">All branches</a>
          {% for bra in links %}
          <a class="dropdown-item" href="{{bra.get_url}}">{{bra.name}}</a>
            {% endfor %}
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://127.0.0.1:8000/office/register">Register</a>
      </li>
    </ul>
      <form action="http://127.0.0.1:8000/office/login" method="get">
        <button class="btn btn-outline-success" type="submit">Login</button>
    </form>
  </div>
</nav>

bankingproject/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New</title>
</head>
<body style="margin-top:200px">
<form  action="new"   method="post" >
    {% csrf_token %}


    <a href="http://127.0.0.1:8000/office/personal_info" class="btn btn-success " style="background-color:yellow;font-size:30px;text-align:center;"><h2>Click here</h2></a>

</form>

</body>
</html>

bankingproject/templates/personal_info.html
<!DOCTYPE html>
<html lang="en">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<head>

    <title>Personalinfo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<!--  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->



</head>
<body>
<div class="container">
    <div class="jumbotron text-center bg-success text-white">
      <h1>Personal Info</h1>

    </div>
    <div class="row pt-3">
      <div class="col-md-12 col-sm-12 col-12 p-2 ">

    <form action="" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3">
              <label for="">Full Name              :</label>
              <input type="text" class="form-control" id="" placeholder="Full Name">
            </div><br>
            <div class="form-row">
            <div class="form-group col-md-3">
              <label for="inputEmail4">DOB         :</label>
              <input type="date" class="form-control" id="inputEmail4" placeholder="Date of birth">
            </div><br>
              <div class="form-row">
            <div class="form-group col-md-3">
              <label for="inputEmail4">Age         :</label>
              <input type="text" class="form-control" id="" placeholder="Enter your age">
            </div><br>
                <div class="form-group col-md-3">
                   <label>Gender       : <br></label><br>
                  <input type="radio" name="Gender" placeholder="enter your Gender">male<br>
                       <input type="radio" name="Gender" placeholder="enter your Gender">female<br>
                </div><br>
            <div class="form-group col-md-3 offset-md-1">
              <label for="inputPassword4">Phone Number :</label>
              <input type="text" class="form-control" id="input Password4" placeholder="Enter your phone number">
            </div>
          </div><br>
                <div class="form-group col-md-3 offset-md-1">
              <label for="inputPassword4">Mail ID :</label>
              <input type="email" class="form-control" id="inputPassword4" placeholder="Enter your email">
            </div>
          </div><br>
                <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label for="inputAddress">Address 1:</label>
                <textarea class="form-control" id="inputAddress" placeholder="Enter your address"></textarea>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="inputAddress2">Address 2 :</label>
                <textarea class="form-control" id="inputAddress2" placeholder="Enter your address 2"></textarea>
              </div>
            </div>
          </div><br>

        {{ personform.as_p }}
                 <div class="form-group col-md-2 other">
              <label class="divOtherState ">Other Branch</label><br>
              <input type="text" class="form-control divOtherBranch" id="dpdlOtherBranch" placeholder="Other Branch">
            </div><br>
        </div><br>
             <div class="form-group col-md-2">
              <label for="inputState">Account type :</label>
              <select id="dpdlAccount type" class="form-control">
                <option selected>Savings account</option>
                <option selected>Current accoount</option>


<!--                <option selected>choose Account type</option>-->
              </select>
            </div><br>
             <div class="form-group col-md-2 other">
               <label>Materials Provide          : </label><br><input type="checkbox" name="materials" placeholder="enter your priorities">Debit card<br>
                       <input type="checkbox" name="materials" placeholder="enter your Gender">Credit card<br>
                       <input type="checkbox" name="materials" placeholder="enter your Gender">Cheque book<br>
            </div><br>
            <div><br>
                <div><br>

              <a href="http://127.0.0.1:8000/office/form" class="btn btn-warning">Submit</a><br>
            <a href="http://127.0.0.1:8000/" class="btn btn-primary">Logout</a><br>
                    </div>
                </div>
    </form>

    <script>
        $(document).ready(function(){

            $('#id_districts').empty();

            var mStrings = JSON.parse('{{ json_m_strings | escapejs }}');
            var eStrings = JSON.parse('{{ json_e_strings | escapejs }}');
            var kStrings = JSON.parse('{{ json_k_strings | escapejs }}');
            var wStrings = JSON.parse('{{ json_w_strings | escapejs }}');
            var tStrings = JSON.parse('{{ json_t_strings | escapejs }}');

  $('#id_branch').on('change', function(){

                var branch = $('#id_branch').val();

                if(branch == 'Malappuram'){

                    $('#id_districts').empty();

                    var length = mStrings.length;
                    var i;
                    for(i=0; i < length; i++){

                         districts= mStrings[i];
                        $('#id_districts').append(

                            `
                            <option value="${districts}">
                                ${districts}
                            </option>
                            `

                        );

                    }

                }

                else if(branch == 'Eranakkulam'){

                    $('#id_districts').empty();

                    var length = eStrings.length;
                    var i;
                    for(i=0; i < length; i++){

                       districts = eStrings[i];
                        $('#id_districts').append(

                            `
                            <option value="${districts}">
                                ${districts}
                            </option>
                            `

                        );

                    }

                }
                else if(branch== 'Kozhikode'){

                    $('#id_districts').empty();

                    var length = kStrings.length;
                    var i;
                    for(i=0; i < length; i++){

                      districts = kStrings[i];
                        $('#id_districts').append(

                            `
                            <option value="${districts}">
                                ${districts}
                            </option>
                            `

                        );

                    }

                }
                else if(branch == 'Wayanad'){

                    $('#id_districts').empty();

                    var length = wStrings.length;
                    var i;
                    for(i=0; i < length; i++){

                        districts = wStrings[i];
                        $('#id_districts').append(

                            `
                            <option value="${districts}">
                                ${districts}
                            </option>
                            `

                        );

                    }

                }
                else if(branch == 'Thrissur'){

                    $('#id_districts').empty();

                    var length = tStrings.length;
                    var i;
                    for(i=0; i < length; i++){

                        districts= tStrings[i];
                        $('#id_districts').append(

                            `
                            <option value="${districts}">
                                ${districts}
                            </option>
                            `

                        );

                    }

                }


                else{

                    $('#id_districts').empty();

                }

            });

        });
    </script>

</body>
</html>

bankingproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
      form{;text-align:center; }
      body
    </style>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>


<body style="background-color:#66CDAA;" >
<h2   style="text-align:center">REGISTRATION</h2>
<form  action="register" method="POST"  >
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>
<!--    <input type="text" name="first_name" placeholder="enter your first_name"><br>-->
<!--    <input type="text" name="last_name" placeholder="enter your last_name"><br>-->
<!--    <input type="email" name="email" placeholder="enter your email"><br>-->
    <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="password" name="password1" placeholder="Confirm your password"><br>
     <input type="submit">

</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>